#pragma config(Motor,  port1,           BackRight,     tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BottomLift,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightLiftTop,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           LeftLiftTop,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           mobileLift,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Sprocket,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          BackLeft,      tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include  "GitHub/Shared/Competition.h"

void drivestraight(int speed, int duration) {
	motor[FrontRight] = speed;
	motor[FrontLeft] = speed;
	motor[BackRight] = speed;
	motor[BackLeft] = speed;
	wait1Msec(duration);
}

void pointturn(int speed, int duration) {
	motor[FrontRight] = speed;
	motor[BackRight] = speed;
	motor[FrontLeft] = -speed;
	motor[BackLeft] = -speed;
}
void sprocketChain(int speed, int duration) {
	motor[Sprocket] = speed;
	wait1Msec(duration);
}

void OpenCloseClaw(int speed, int duration) {
	motor[Claw] = speed;
	wait1Msec(duration);
}

void liftBtm(int speed, int duration) {
	motor[BottomLift] = speed;
	wait1Msec(duration);
}
void liftTop(int speed, int duration) {
	motor[RightLiftTop] = speed;
	motor[LeftLiftTop] = speed;
	wait1Msec(duration);
}
void liftAll(int speed, int duration) {
	motor[RightLiftTop] = speed;
	motor[LeftLiftTop] = speed;
	motor[BottomLift] = speed;
	wait1Msec(duration);
}

void autonomous (){
/*
	crab(60,600);
	drivestraight(70, 1800);//drive forward
	crab(-60,500);
	drivestraight(70, 950);
	crab(70, 1000);//close claw on mobile ghoul 0_0
	motor[Claw] = 40;//keep claw closed
	lift(70,500);//lift slightly off the ground
	motor[Claw] = 15;
	motor[M6] = 15; //keep claw lifted
	motor[M7] = 15;//keep claw lifted
	pointturn(50,200);
	drivestraight(50,100);
	pointturn(70, 2450); //turn left A LOT
	drivestraight(70,3900); //drive to scoring zone
	pointturn(70, 1200);
	motor[Claw] = -50;
	motor[M6] = 50; //keep claw lifted
	motor[M7] = 50;//keep claw lifted
	lift(-20,800); //put mobile goal down
	crab(-70,700); //let go of mobile goal
	drivestraight(-70,500); //back up
*/

	}


//autonomouse
void autonomous () {


}

void joystick () {
}
